# Generated by Django 3.1.7 on 2021-07-15 09:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=1000)),
                ('user_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='pinvalid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('instantpin', models.IntegerField(default=False)),
                ('created_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=15)),
                ('birthday', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('message', models.CharField(max_length=900)),
            ],
            options={
                'verbose_name': 'Support',
                'verbose_name_plural': 'Support',
            },
        ),
        migrations.CreateModel(
            name='userpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.CharField(blank=True, max_length=100)),
                ('emoji', models.FilePathField(blank=True)),
                ('usercontent', models.TextField(blank=True, max_length=1000)),
                ('userfile', models.FileField(blank=True, upload_to='user_post')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.registration')),
                ('liked', models.ManyToManyField(related_name='likes', to='home.registration')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], max_length=8)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.userpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.registration')),
            ],
        ),
    ]
