# Generated by Django 3.0.2 on 2021-03-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support',
            options={'verbose_name': 'Support', 'verbose_name_plural': 'Support'},
        ),
    ]
